/**
  * <summary>
  *   Extra / additional functions which apply rotations
  * </summary>
  *//** */

#if defined _inc_rotation_extra_
	#endinput
#else
    #define _inc_rotation_extra_
#endif

#include "rotation"

#if defined DEBUG
    #define debug printf
#else
    #define debug(%0\10
#endif

#include "rotation_extra\rotation_extra_object"
#include "rotation_extra\rotation_extra_player"
#include "rotation_extra\rotation_extra_vehicle"
#include "rotation_extra\rotation_extra_dynamic"

#undef debug